# fly.toml app configuration file generated for spark-nwc on 2025-04-16T18:03:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spark-nwc'
primary_region = 'fra'

[build]

[env]
  BASE_URL = 'https://spark-nwc.fly.dev'
  DATABASE_URL = 'file:/data/spark-nwc.db'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '1m0s'
    timeout = '5s'
    grace_period = '45s'
    method = 'GET'
    path = '/ping'

[mounts]
  source = "spark_nwc_data"
  destination = "/data"
  initial_size = '1'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
